# Generated by Django 4.1 on 2022-08-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='order',
            new_name='order_id',
        ),
    ]
