# Generated by Django 4.1 on 2022-08-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_ordereditem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='order_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.order'),
        ),
    ]
